name: convoweb
version: 0.0.1
author: Richard Griffith <scribe.griff@gmail.com>
description: A Signal Processing Web Application for Dart
homepage: http://www.scribegriff.com
dependencies:
  convolab:
    git: git://github.com/scribeGriff/ConvoLab.git
  unittest: any
  browser: any
  meta: any
